package version

// Version of the twelvedata CLI.
// Do not edit — regenerated by the build pipeline.
// `var` (not `const`) so goreleaser can override at link time via -ldflags -X.
var Version = "1.0.9"
